services:
  blogging_app:
    image: blogging_app:1.0.0
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  postgres_data:
    driver: local